### PR TITLE
Handle constraints change, notably video or audio device id

### PR DESCRIPTION
**Pull request by antoinedejonckheere**

### CODE REVIEW

**Comment by rico345100** [comment]
Hello @antoinedejonckheere , thanks for PR! Could you explain what this PR do more specifically?

**Comment by antoinedejonckheere** [comment]
> Hello @antoinedejonckheere , thanks for PR! Could you explain what this PR do more specifically?

Hi @rico345100 yes sure.
I am using `react-multimedia-capture` in a video chat app that I am building for jetpackAI ( https://github.com/jetpackAI ). One of the feature of this app is to record the video stream coming from the camera connected to the computer.

In the app, our users can possibly choose between different cameras. When the app starts, the default camera is chosen (i.e the computer webcam).

Without the changes brought in this PR, if the user picks another camera and starts recording the video stream, the default webcam video stream is captured instead of the one chosen by the user.

Don't hesitate reaching out to me should you have any more question or remark.

**Comment by rico345100** [comment]
PR Merged! I will publish to npm asap. Thanks to improve this module!

**Comment by antoinedejonckheere** [comment]
> PR Merged! I will publish to npm asap. Thanks to improve this module!

@rico345100 you're most welcome.

**Pull request merged**
